name: CI

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - uses: pandoc/actions/setup@v1
        with:
          version: 3.2.1
      - uses: astral-sh/setup-uv@v5
        with:
          version: 0.5.18
      - name: Build
        run: make build
      - name: Deploy
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: sumeetb-dev
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}